services:
  mongodb:
    image: mongo:latest
    container_name: energply_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: energply_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongodb

volumes:
  mongo_data: